name: update
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: update
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: install packages
      run: sudo apt-get update && sudo apt-get install -y cmake g++ git gnuplot

    - name: download generator
      run: gh repo clone acodcha/ti4-echelon generator
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: configure generator
      run: cd generator && mkdir -p build && cd build && cmake ..

    - name: build generator
      run: cd generator/build && make

    - name: delete previous leaderboard
      run: rm -rf leaderboard/*

    - name: generate new leaderboard
      run: ./generator/build/bin/ti4-echelon --games games.txt --leaderboard leaderboard

    - name: cleanup generator
      run: rm -rf generator

    - name: configure git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: commit leaderboard files
      run: |
        git add leaderboard
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update leaderboard"
          git pull --rebase origin ${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }}
        fi
